namespace plt0_gui
{
    partial class plt0_gui
    {
        private System.Windows.Forms.Label output_file_type_label;
        private System.Windows.Forms.Label mandatory_settings_label;
        private System.Windows.Forms.Label bmd_label;
        private System.Windows.Forms.PictureBox bti_ck;
        private System.Windows.Forms.Label bti_label;
        private System.Windows.Forms.PictureBox tex0_ck;
        private System.Windows.Forms.Label tex0_label;
        private System.Windows.Forms.PictureBox tpl_ck;
        private System.Windows.Forms.Label tpl_label;
        private System.Windows.Forms.PictureBox bmp_ck;
        private System.Windows.Forms.Label bmp_label;
        private System.Windows.Forms.PictureBox png_ck;
        private System.Windows.Forms.Label png_label;
        private System.Windows.Forms.PictureBox jpg_ck;
        private System.Windows.Forms.Label jpg_label;
        private System.Windows.Forms.PictureBox tiff_ck;
        private System.Windows.Forms.Label tiff_label;
        private System.Windows.Forms.PictureBox tif_ck;
        private System.Windows.Forms.Label tif_label;
        private System.Windows.Forms.PictureBox ico_ck;
        private System.Windows.Forms.Label ico_label;
        private System.Windows.Forms.PictureBox gif_ck;
        private System.Windows.Forms.Label gif_label;
        private System.Windows.Forms.PictureBox jpeg_ck;
        private System.Windows.Forms.Label jpeg_label;
        private System.Windows.Forms.Label options_label;
        private System.Windows.Forms.PictureBox warn_ck;
        private System.Windows.Forms.Label warn_label;
        private System.Windows.Forms.PictureBox stfu_ck;
        private System.Windows.Forms.Label stfu_label;
        private System.Windows.Forms.PictureBox safe_mode_ck;
        private System.Windows.Forms.Label safe_mode_label;
        private System.Windows.Forms.PictureBox reversey_ck;
        private System.Windows.Forms.Label reversey_label;
        private System.Windows.Forms.PictureBox random_ck;
        private System.Windows.Forms.Label random_label;
        private System.Windows.Forms.PictureBox no_warning_ck;
        private System.Windows.Forms.Label no_warning_label;
        private System.Windows.Forms.PictureBox funky_ck;
        private System.Windows.Forms.Label funky_label;
        private System.Windows.Forms.PictureBox FORCE_ALPHA_ck;
        private System.Windows.Forms.Label FORCE_ALPHA_label;
        private System.Windows.Forms.PictureBox bmp_32_ck;
        private System.Windows.Forms.Label bmp_32_label;
        private System.Windows.Forms.PictureBox ask_exit_ck;
        private System.Windows.Forms.Label ask_exit_label;
        private System.Windows.Forms.PictureBox cmpr_ck;
        private System.Windows.Forms.Label cmpr_label;
        private System.Windows.Forms.PictureBox ci14x2_ck;
        private System.Windows.Forms.Label ci14x2_label;
        private System.Windows.Forms.PictureBox ci8_ck;
        private System.Windows.Forms.Label ci8_label;
        private System.Windows.Forms.PictureBox ci4_ck;
        private System.Windows.Forms.Label ci4_label;
        private System.Windows.Forms.PictureBox rgba32_ck;
        private System.Windows.Forms.Label rgba32_label;
        private System.Windows.Forms.PictureBox rgb5a3_ck;
        private System.Windows.Forms.Label rgb5a3_label;
        private System.Windows.Forms.PictureBox rgb565_ck;
        private System.Windows.Forms.Label rgb565_label;
        private System.Windows.Forms.PictureBox ai8_ck;
        private System.Windows.Forms.Label ai8_label;
        private System.Windows.Forms.PictureBox ai4_ck;
        private System.Windows.Forms.Label ai4_label;
        private System.Windows.Forms.PictureBox i8_ck;
        private System.Windows.Forms.Label i8_label;
        private System.Windows.Forms.PictureBox i4_ck;
        private System.Windows.Forms.Label i4_label;
        private System.Windows.Forms.Label encoding_label;
        private System.Windows.Forms.PictureBox surrounding_ck;
        private System.Windows.Forms.PictureBox algo_4_ck;
        private System.Windows.Forms.Label algo_4_label;
        private System.Windows.Forms.PictureBox algo_2_ck;
        private System.Windows.Forms.Label algo_2_label;
        private System.Windows.Forms.PictureBox cie_709_ck;
        private System.Windows.Forms.Label cie_709_label;
        private System.Windows.Forms.PictureBox cie_601_ck;
        private System.Windows.Forms.Label cie_601_label;
        private System.Windows.Forms.Label algorithm_label;
        private System.Windows.Forms.PictureBox mix_ck;
        private System.Windows.Forms.Label mix_label;
        private System.Windows.Forms.PictureBox alpha_ck;
        private System.Windows.Forms.Label alpha_label;
        private System.Windows.Forms.PictureBox no_alpha_ck;
        private System.Windows.Forms.Label no_alpha_label;
        private System.Windows.Forms.Label alpha_title;
        private System.Windows.Forms.PictureBox Tmirror_ck;
        private System.Windows.Forms.Label Tmirror_label;
        private System.Windows.Forms.PictureBox Trepeat_ck;
        private System.Windows.Forms.Label Trepeat_label;
        private System.Windows.Forms.PictureBox Tclamp_ck;
        private System.Windows.Forms.Label Tclamp_label;
        private System.Windows.Forms.Label WrapT_label;
        private System.Windows.Forms.PictureBox Smirror_ck;
        private System.Windows.Forms.Label Smirror_label;
        private System.Windows.Forms.PictureBox Srepeat_ck;
        private System.Windows.Forms.Label Srepeat_label;
        private System.Windows.Forms.PictureBox Sclamp_ck;
        private System.Windows.Forms.Label Sclamp_label;
        private System.Windows.Forms.Label WrapS_label;
        private System.Windows.Forms.Label magnification_label;
        private System.Windows.Forms.Label minification_label;
        private System.Windows.Forms.PictureBox min_linearmipmaplinear_ck;
        private System.Windows.Forms.Label min_linearmipmaplinear_label;
        private System.Windows.Forms.PictureBox min_linearmipmapnearest_ck;
        private System.Windows.Forms.Label min_linearmipmapnearest_label;
        private System.Windows.Forms.PictureBox min_nearestmipmaplinear_ck;
        private System.Windows.Forms.Label min_nearestmipmaplinear_label;
        private System.Windows.Forms.PictureBox min_nearestmipmapnearest_ck;
        private System.Windows.Forms.Label min_nearestmipmapnearest_label;
        private System.Windows.Forms.PictureBox min_linear_ck;
        private System.Windows.Forms.Label min_linear_label;
        private System.Windows.Forms.PictureBox min_nearest_neighbour_ck;
        private System.Windows.Forms.Label min_nearest_neighbour_label;
        private System.Windows.Forms.PictureBox mag_linearmipmaplinear_ck;
        private System.Windows.Forms.Label mag_linearmipmaplinear_label;
        private System.Windows.Forms.PictureBox mag_linearmipmapnearest_ck;
        private System.Windows.Forms.Label mag_linearmipmapnearest_label;
        private System.Windows.Forms.PictureBox mag_nearestmipmaplinear_ck;
        private System.Windows.Forms.Label mag_nearestmipmaplinear_label;
        private System.Windows.Forms.PictureBox mag_nearestmipmapnearest_ck;
        private System.Windows.Forms.Label mag_nearestmipmapnearest_label;
        private System.Windows.Forms.PictureBox mag_linear_ck;
        private System.Windows.Forms.Label mag_linear_label;
        private System.Windows.Forms.PictureBox mag_nearest_neighbour_ck;
        private System.Windows.Forms.Label mag_nearest_neighbour_label;
        private System.Windows.Forms.PictureBox r_r_ck;
        private System.Windows.Forms.PictureBox r_g_ck;
        private System.Windows.Forms.PictureBox g_r_ck;
        private System.Windows.Forms.PictureBox g_g_ck;
        private System.Windows.Forms.PictureBox a_g_ck;
        private System.Windows.Forms.PictureBox a_r_ck;
        private System.Windows.Forms.PictureBox b_g_ck;
        private System.Windows.Forms.PictureBox b_r_ck;
        private System.Windows.Forms.PictureBox g_a_ck;
        private System.Windows.Forms.PictureBox g_b_ck;
        private System.Windows.Forms.PictureBox r_a_ck;
        private System.Windows.Forms.PictureBox r_b_ck;
        private System.Windows.Forms.PictureBox a_a_ck;
        private System.Windows.Forms.PictureBox a_b_ck;
        private System.Windows.Forms.PictureBox b_a_ck;
        private System.Windows.Forms.PictureBox b_b_ck;
        private System.Windows.Forms.Label colour_channels_label;
        private System.Windows.Forms.PictureBox view_alpha_ck;
        private System.Windows.Forms.Label view_alpha_label;
        private System.Windows.Forms.PictureBox view_algorithm_ck;
        private System.Windows.Forms.Label view_algorithm_label;
        private System.Windows.Forms.PictureBox view_WrapS_ck;
        private System.Windows.Forms.Label view_WrapS_label;
        private System.Windows.Forms.PictureBox view_WrapT_ck;
        private System.Windows.Forms.Label view_WrapT_label;
        private System.Windows.Forms.PictureBox view_mag_ck;
        private System.Windows.Forms.Label view_mag_label;
        private System.Windows.Forms.PictureBox view_min_ck;
        private System.Windows.Forms.Label view_min_label;
        private System.Windows.Forms.PictureBox banner_ck;
        private System.Windows.Forms.PictureBox all_ck;
        private System.Windows.Forms.PictureBox preview_ck;
        private System.Windows.Forms.PictureBox auto_ck;
        private System.Windows.Forms.PictureBox paint_ck;
        private System.Windows.Forms.PictureBox banner_x_ck;
        private System.Windows.Forms.PictureBox banner_f11_ck;
        private System.Windows.Forms.PictureBox banner_minus_ck;
        private System.Windows.Forms.PictureBox banner_9_ck;
        private System.Windows.Forms.PictureBox banner_8_ck;
        private System.Windows.Forms.PictureBox banner_7_ck;
        private System.Windows.Forms.PictureBox banner_6_ck;
        private System.Windows.Forms.PictureBox banner_4_ck;
        private System.Windows.Forms.PictureBox banner_3_ck;
        private System.Windows.Forms.PictureBox banner_2_ck;
        private System.Windows.Forms.PictureBox banner_1_ck;
        private System.Windows.Forms.PictureBox cli_textbox_ck;
        private System.Windows.Forms.PictureBox run_ck;
        private System.Windows.Forms.TextBox input_file_txt;
        private System.Windows.Forms.Label input_file_label;
        private System.Windows.Forms.Label input_file2_label;
        private System.Windows.Forms.TextBox input_file2_txt;
        private System.Windows.Forms.Label mipmaps_label;
        private System.Windows.Forms.TextBox mipmaps_txt;
        private System.Windows.Forms.Label diversity_label;
        private System.Windows.Forms.TextBox diversity_txt;
        private System.Windows.Forms.Label diversity2_label;
        private System.Windows.Forms.TextBox diversity2_txt;
        private System.Windows.Forms.Label percentage_label;
        private System.Windows.Forms.TextBox percentage_txt;
        private System.Windows.Forms.Label percentage2_label;
        private System.Windows.Forms.TextBox percentage2_txt;
        private System.Windows.Forms.Label cmpr_max_label;
        private System.Windows.Forms.TextBox cmpr_max_txt;
        private System.Windows.Forms.Label output_name_label;
        private System.Windows.Forms.TextBox output_name_txt;
        private System.Windows.Forms.Label cmpr_min_alpha_label;
        private System.Windows.Forms.TextBox cmpr_min_alpha_txt;
        private System.Windows.Forms.Label num_colours_label;
        private System.Windows.Forms.TextBox num_colours_txt;
        private System.Windows.Forms.Label round3_label;
        private System.Windows.Forms.TextBox round3_txt;
        private System.Windows.Forms.Label round4_label;
        private System.Windows.Forms.TextBox round4_txt;
        private System.Windows.Forms.Label round5_label;
        private System.Windows.Forms.TextBox round5_txt;
        private System.Windows.Forms.Label round6_label;
        private System.Windows.Forms.TextBox round6_txt;
        private System.Windows.Forms.Label custom_a_label;
        private System.Windows.Forms.TextBox custom_a_txt;
        private System.Windows.Forms.Label custom_b_label;
        private System.Windows.Forms.TextBox custom_b_txt;
        private System.Windows.Forms.Label custom_g_label;
        private System.Windows.Forms.TextBox custom_g_txt;
        private System.Windows.Forms.Label custom_r_label;
        private System.Windows.Forms.TextBox custom_r_txt;
        private System.Windows.Forms.Label custom_rgba_label;
        private System.Windows.Forms.Label description_title;
        private System.Windows.Forms.Label description;
        private System.Windows.Forms.PictureBox palette_rgb5a3_ck;
        private System.Windows.Forms.Label palette_rgb5a3_label;
        private System.Windows.Forms.PictureBox palette_rgb565_ck;
        private System.Windows.Forms.Label palette_rgb565_label;
        private System.Windows.Forms.PictureBox palette_ai8_ck;
        private System.Windows.Forms.Label palette_ai8_label;
        private System.Windows.Forms.Label palette_label;
        private System.Windows.Forms.PictureBox github_ck;
        private System.Windows.Forms.PictureBox youtube_ck;
        private System.Windows.Forms.PictureBox discord_ck;
        private System.Windows.Forms.Label desc2;
        private System.Windows.Forms.Label desc3;
        private System.Windows.Forms.Label desc4;
        private System.Windows.Forms.Label desc5;
        private System.Windows.Forms.Label desc6;
        private System.Windows.Forms.Label desc7;
        private System.Windows.Forms.Label desc8;
        private System.Windows.Forms.Label desc9;
        private System.Windows.Forms.Label output_label;
        private System.Windows.Forms.PictureBox version_ck;
        private System.Windows.Forms.Label cli_textbox_label;
        private System.Windows.Forms.PictureBox view_rgba_ck;
        private System.Windows.Forms.Label view_rgba_label;
        private System.Windows.Forms.PictureBox view_palette_ck;
        private System.Windows.Forms.Label view_palette_label;
        private System.Windows.Forms.PictureBox view_cmpr_ck;
        private System.Windows.Forms.Label view_cmpr_label;
        private System.Windows.Forms.PictureBox view_options_ck;
        private System.Windows.Forms.Label view_options_label;
        private System.Windows.Forms.Label banner_resize;
        private System.Windows.Forms.PictureBox textchange_ck;
        private System.Windows.Forms.Label textchange_label;
        private System.Windows.Forms.PictureBox auto_update_ck;
        private System.Windows.Forms.Label auto_update_label;
        private System.Windows.Forms.PictureBox sync_preview_ck;
        private System.Windows.Forms.PictureBox upscale_ck;
        private System.Windows.Forms.Label upscale_label;
        private System.Windows.Forms.Label banner_move;
        // private System.Windows.Forms.PictureBox image_ck;  // uncomment this line to unlock the designer, and comment another line on plt0-v.cs  ->             this.image_ck.InterpolationMode = InterpolationMode.NearestNeighbor;
        // edit: just compile and launch once, then the designer will be unlocked with this PictureBoxWithInterpolationMode
        private PictureBoxWithInterpolationMode image_ck;
        private System.Windows.Forms.Label preview4k_label;
        private System.Windows.Forms.PictureBox preview4k_ck;
        private System.Windows.Forms.PictureBox reversex_ck;
        private System.Windows.Forms.Label reversex_label;
        private System.Windows.Forms.Label cmpr_c1_label;
        private System.Windows.Forms.TextBox cmpr_c1_txt;
        private System.Windows.Forms.Label cmpr_c1;
        private System.Windows.Forms.Label cmpr_c2;
        private System.Windows.Forms.Label cmpr_c2_label;
        private System.Windows.Forms.TextBox cmpr_c2_txt;
        private System.Windows.Forms.Label cmpr_c3;
        private System.Windows.Forms.Label cmpr_c3_label;
        private System.Windows.Forms.TextBox cmpr_c3_txt;
        private System.Windows.Forms.Label cmpr_c4;
        private System.Windows.Forms.Label cmpr_c4_label;
        private System.Windows.Forms.TextBox cmpr_c4_txt;
        private System.Windows.Forms.PictureBox cmpr_swap_ck;
        private System.Windows.Forms.Label cmpr_swap_label;
        private System.Windows.Forms.PictureBox cmpr_block_paint_ck;
        private System.Windows.Forms.Label cmpr_block_paint_label;
        private System.Windows.Forms.PictureBox cmpr_block_selection_ck;
        private System.Windows.Forms.Label cmpr_block_selection_label;
        private PictureBoxWithInterpolationMode cmpr_preview_ck;
        private System.Windows.Forms.Label cmpr_picture_tooltip_label;
        private System.Windows.Forms.Label cmpr_selected_block_label;
        private System.Windows.Forms.PictureBox cmpr_save_ck;
        private System.Windows.Forms.PictureBox cmpr_save_as_ck;
        private System.Windows.Forms.Label cmpr_warning;
        private System.Windows.Forms.Label cmpr_sel_label;
        private System.Windows.Forms.Label cmpr_mouse1_label;
        private System.Windows.Forms.Label cmpr_mouse2_label;
        private System.Windows.Forms.Label cmpr_mouse4_label;
        private System.Windows.Forms.Label cmpr_mouse3_label;
        private System.Windows.Forms.Label cmpr_mouse5_label;
        private System.Windows.Forms.Label cmpr_sel;
        private System.Windows.Forms.PictureBox bmd_ck;
        private PictureBoxWithInterpolationMode cmpr_grid_ck;
        private System.Windows.Forms.Label cmpr_hover_colour;
        private System.Windows.Forms.Label cmpr_hover_colour_label;
        private System.Windows.Forms.TextBox cmpr_hover_colour_txt;
        private System.Windows.Forms.Label cmpr_edited_colour;
        private System.Windows.Forms.Label cmpr_edited_colour_label;
        private System.Windows.Forms.TextBox cmpr_edited_colour_txt;
        private System.Windows.Forms.PictureBox name_string_ck;
        private System.Windows.Forms.Label name_string_label;
        private System.Windows.Forms.PictureBox cmpr_swap2_ck;
        private System.Windows.Forms.Label cmpr_swap2_label;
        private PictureBoxWithInterpolationMode cmpr_palette;
        private System.Windows.Forms.PictureBox cmpr_hover_ck;
        private System.Windows.Forms.Label cmpr_hover_label;
        private System.Windows.Forms.PictureBox cmpr_update_preview_ck;
        private System.Windows.Forms.Label cmpr_update_preview_label;
        private System.Windows.Forms.PictureBox banner_global_move_ck;
        private System.Windows.Forms.PictureBox banner_5_ck;
        private System.Windows.Forms.PictureBox banner_11_ck;
        private System.Windows.Forms.PictureBox banner_12_ck;
        private System.Windows.Forms.PictureBox banner_13_ck;
        private System.Windows.Forms.PictureBox banner_14_ck;
        private System.Windows.Forms.PictureBox banner_16_ck;
        private System.Windows.Forms.PictureBox banner_17_ck;
        private System.Windows.Forms.PictureBox banner_18_ck;
        private System.Windows.Forms.PictureBox banner_19_ck;
        private System.Windows.Forms.PictureBox banner_15_ck;
        private System.Windows.Forms.Label pal_cie_label;
        private System.Windows.Forms.Label pal_rgb_label;
        private System.Windows.Forms.Label algo_5_label;
        private System.Windows.Forms.PictureBox pal_rgb_ck;
        private System.Windows.Forms.PictureBox pal_cie_ck;
        private System.Windows.Forms.PictureBox algo_5_ck;
        private System.Windows.Forms.Label algo_3_label;
        private System.Windows.Forms.PictureBox algo_3_ck;
        private System.Windows.Forms.Label distance_label;
        private System.Windows.Forms.PictureBox decode_ck;
        private System.Windows.Forms.PictureBox palette_banner_ck;
        private System.Windows.Forms.PictureBox settings_banner_ck;
        private System.Windows.Forms.PictureBox view_cli_param_ck;
        private System.Windows.Forms.Label view_cli_param_label;
        private System.Windows.Forms.PictureBox opening_banner_ck;
        private System.Windows.Forms.TextBox textBox3;
        private System.Windows.Forms.TextBox textBox1;
        private System.Windows.Forms.TextBox textBox2;
        private System.Windows.Forms.TextBox textBox4;
        private System.Windows.Forms.TextBox textBox5;
        private System.Windows.Forms.TextBox textBox6;
        private System.Windows.Forms.TextBox textBox7;
        private System.Windows.Forms.TextBox textBox8;
        private System.Windows.Forms.TextBox textBox9;
        private System.Windows.Forms.TextBox textBox10;
        private System.Windows.Forms.TextBox textBox11;
        private System.Windows.Forms.TextBox textBox12;
        private System.Windows.Forms.TextBox textBox13;
        private System.Windows.Forms.TextBox textBox14;
        private System.Windows.Forms.TextBox textBox15;
        private System.Windows.Forms.TextBox textBox16;
        private System.Windows.Forms.TextBox textBox17;
        private System.Windows.Forms.TextBox textBox18;
        private System.Windows.Forms.TextBox textBox19;
        private System.Windows.Forms.TextBox textBox20;
        private System.Windows.Forms.TextBox textBox21;
        private System.Windows.Forms.TextBox textBox22;
        private System.Windows.Forms.TextBox textBox23;
        private System.Windows.Forms.TextBox textBox24;
        private System.Windows.Forms.TextBox textBox25;
        private System.Windows.Forms.TextBox textBox26;
        private System.Windows.Forms.TextBox textBox27;
        private System.Windows.Forms.TextBox textBox28;
        private System.Windows.Forms.TextBox textBox29;
        private System.Windows.Forms.TextBox textBox30;
        /*
/// <summary>
/// Required designer variable.
/// </summary>
private System.ComponentModel.IContainer components = null;

/// <summary>
/// Clean up any resources being used.
/// </summary>
/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
protected override void Dispose(bool disposing)
{
if (disposing && (components != null))
{
components.Dispose();
}
base.Dispose(disposing);
}

#region Windows Form Designer generated code

/// <summary>
/// Required method for Designer support - do not modify
/// the contents of this method with the code editor.
/// </summary>
private void InitializeComponent()
{
this.SuspendLayout();
// 
// Form1
// 
this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
this.ClientSize = new System.Drawing.Size(800, 450);
this.Name = "Form1";
this.Text = "Updater";
this.ResumeLayout(false);

}

#endregion
*/
    }
}

